version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Installing dependencies..."
      - composer install --no-interaction --no-progress --no-suggest --v
  build:
    commands:
      - echo "Building project..."
      # Add any build commands here
  post_build:
    commands:
      - echo "Running post-build steps..."
      # Add any post-build commands here
artifacts:
  files:
    - '**/*'
  discard-paths: yes
