version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - echo "Installing dependencies..."
      - composer install --no-interaction --no-progress --no-suggest

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      # Add any pre-build commands here

  build:
    commands:
      - echo "Running build steps..."
      - cp application/config/database.sample.php application/config/database.php
      - cp application/config/config.sample.php application/config/config.php
      # Add any build commands here

  post_build:
    commands:
      - echo "Running post-build steps..."
      # Add any post-build commands here

artifacts:
  files:
    - '**/*'
  discard-paths: yes
